/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BallRouteImport } from './routes/ball'
import { Route as FartherRouteImport } from './routes/farther'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BallRoute = BallRouteImport.update({
  id: '/ball',
  path: '/ball',
  getParentRoute: () => rootRouteImport,
} as any)
const FartherRoute = FartherRouteImport.update({
  id: '/farther',
  path: '/farther',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ball' | '/farther'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ball' | '/farther'
  id: '__root__' | '/' | '/ball' | '/farther'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BallRoute: typeof BallRoute
  FartherRoute: typeof FartherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball': {
      id: '/ball'
      path: '/ball'
      fullPath: '/ball'
      preLoaderRoute: typeof BallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farther': {
      id: '/farther'
      path: '/farther'
      fullPath: '/farther'
      preLoaderRoute: typeof FartherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BallRoute: BallRoute,
  FartherRoute: FartherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
