/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BallRouteImport } from './routes/ball'
import { Route as FartherRouteImport } from './routes/farther'
import { Route as FightRouteImport } from './routes/fight'
import { Route as HerRouteImport } from './routes/her'
import { Route as TaleRouteImport } from './routes/tale'
import { Route as WalkRouteImport } from './routes/walk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BallRoute = BallRouteImport.update({
  id: '/ball',
  path: '/ball',
  getParentRoute: () => rootRouteImport,
} as any)
const FartherRoute = FartherRouteImport.update({
  id: '/farther',
  path: '/farther',
  getParentRoute: () => rootRouteImport,
} as any)
const FightRoute = FightRouteImport.update({
  id: '/fight',
  path: '/fight',
  getParentRoute: () => rootRouteImport,
} as any)
const HerRoute = HerRouteImport.update({
  id: '/her',
  path: '/her',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleRoute = TaleRouteImport.update({
  id: '/tale',
  path: '/tale',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkRoute = WalkRouteImport.update({
  id: '/walk',
  path: '/walk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
  '/fight': typeof FightRoute
  '/her': typeof HerRoute
  '/tale': typeof TaleRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
  '/fight': typeof FightRoute
  '/her': typeof HerRoute
  '/tale': typeof TaleRoute
  '/walk': typeof WalkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ball': typeof BallRoute
  '/farther': typeof FartherRoute
  '/fight': typeof FightRoute
  '/her': typeof HerRoute
  '/tale': typeof TaleRoute
  '/walk': typeof WalkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ball' | '/farther' | '/fight' | '/her' | '/tale' | '/walk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ball' | '/farther' | '/fight' | '/her' | '/tale' | '/walk'
  id:
    | '__root__'
    | '/'
    | '/ball'
    | '/farther'
    | '/fight'
    | '/her'
    | '/tale'
    | '/walk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BallRoute: typeof BallRoute
  FartherRoute: typeof FartherRoute
  FightRoute: typeof FightRoute
  HerRoute: typeof HerRoute
  TaleRoute: typeof TaleRoute
  WalkRoute: typeof WalkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball': {
      id: '/ball'
      path: '/ball'
      fullPath: '/ball'
      preLoaderRoute: typeof BallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farther': {
      id: '/farther'
      path: '/farther'
      fullPath: '/farther'
      preLoaderRoute: typeof FartherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fight': {
      id: '/fight'
      path: '/fight'
      fullPath: '/fight'
      preLoaderRoute: typeof FightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/her': {
      id: '/her'
      path: '/her'
      fullPath: '/her'
      preLoaderRoute: typeof HerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tale': {
      id: '/tale'
      path: '/tale'
      fullPath: '/tale'
      preLoaderRoute: typeof TaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walk': {
      id: '/walk'
      path: '/walk'
      fullPath: '/walk'
      preLoaderRoute: typeof WalkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BallRoute: BallRoute,
  FartherRoute: FartherRoute,
  FightRoute: FightRoute,
  HerRoute: HerRoute,
  TaleRoute: TaleRoute,
  WalkRoute: WalkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
